theme: ocean
day_night: true
font: ''
font_size: M
site_type: Person
local_business_type: ''
org_name: ''
description: ''
highlight: true
highlight_languages:
  - r
math: false
diagram: false
privacy_pack: false
edit_page:
  repo_url: 'https://github.com/gcushen/hugo-academic'
  content_dir: ''
  repo_branch: master
  editable:
    docs: true
    page: false
    post: false
email: kshankar@usm.my
phone: +604 653 4632
address:
  street: >-
    National Advanced IPv6 Centre (NAv6), Level 6, School of Computer Sciences
    Building, Universiti Sains Malaysia
  city: USM
  region: Penang
  postcode: '11800'
  country: Malaysia
  country_code: MY
coordinates:
  latitude: '5.354623'
  longitude: '100.301446'
directions: >-
  Take the lift to the 6th floor and turn right at the entrance to head over to
  NAv6.
office_hours: []
appointment_url: 'https://calendly.com/kshankar_usm'
contact_links:
  - icon: twitter
    icon_pack: fab
    name: DM Me
    link: 'https://twitter.com/sh_nk_r'
  - icon: skype
    icon_pack: fab
    name: Skype Me
    link: 'skype:shankar.karuppayah?call'
  - icon: telegram
    icon_pack: fab
    name: Telegram Me
    link: 'https://telegram.me/@skusm'
sharing_image: avatar.jpg
twitter: sh_nk_r
date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: de
main_menu:
  align: l
  show_logo: true
reading_time: true
section_pager: false
docs_section_pager: true
sharing: true
link_authors: true
abstract_length: 135
plugins_js: []
avatar:
  gravatar: false
  shape: circle
address_formats:
  en-us:
    order:
      - street
      - city
      - region
      - postcode
    delimiters:
      - ', '
      - ', '
      - ' '
      - ''
  en-gb:
    order:
      - street
      - city
      - region
      - postcode
    delimiters:
      - ', '
      - ', '
      - ', '
      - ''
  de:
    order:
      - street
      - postcode
      - city
    delimiters:
      - <br>
      - ' '
      - ''
  fr-fr:
    order:
      - street
      - postcode
      - city
    delimiters:
      - <br>
      - ' '
      - ''
  zh:
    order:
      - postcode
      - region
      - city
      - street
    delimiters:
      - ' '
      - ' '
      - ' '
      - ''
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
comments:
  engine: 0
  commentable:
    page: true
    post: true
    docs: true
    project: true
    publication: true
    talk: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  engine: 1
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  engine: 2
  api_key: ''
  zoom: 15
marketing:
  google_analytics: G-X1XQD78B7Q
  google_tag_manager: ''
cms:
  netlify_cms: true
icon:
  pack:
    ai: true